### ISSUE TITLE
Object decorators not working in sync mode

### ISSUE THREAD

**Issue by meain** [silverbulletmd/silverbullet#1002]
[`objectDecorators`](https://silverbullet.md/Object%20Decorators) defined in settings does not seem to apply when in sync mode. The ones defined in the page's frontmatter does work.

**Comment by meain** [comment]
I see the following in the JS console:

![Screenshot 2024-07-30 at 12 40 10 PM](https://github.com/user-attachments/assets/89fad88c-f043-499c-b86b-b39db5dc321e)

**Comment by meain** [comment]
It just started working in sync mode on desktop browser, but not on mobile. I'm starting to think it is possible that it is some syncing issue. The settings page in mobile does have the new content, I also random "Sync now" and "Reload" and a page refresh just in case, but still the same issue.

**Comment by zefhemel** [comment]
This does sound like perhaps the plugs haven't synced locally yet. Can you lead it do a full sync (just keep the page open for some time, 20-30s at least) to make sure this all synced and then reload? For me it works. You can also try on https://silverbullet.md.

**Comment by meain** [comment]
I kept it open for over a minute. There was a point at which I got the `toc` decoration to work, but all the others include decorations defined within the page not working. I also did another round of plug/library update, sync and reload as well.

The logs in the server was relatively silent with it requesting the index page once in a while. I did however see the following error in the logs. The silverbullet-ai plugin was throwing an error (cc @justyns), but then again it is running in a separate worker.

```
An exception was thrown as a result of invoking function indexEmbeddings error: Cannot read properties of undefined (reading 'generateEmbeddings')
Error dispatching event page:index to silverbullet-ai.indexEmbeddings: Cannot read properties of undefined (reading 'generateEmbeddings')
An exception was thrown as a result of invoking function parseIndexTextRepublish error: Cannot read properties of undefined (reading 'generateEmbeddings')
Error dispatching event page:index_text to index.parseIndexTextRepublish: Cannot read properties of undefined (reading 'generateEmbeddings')
Write failed Error: Cannot read properties of undefined (reading 'generateEmbeddings')
    at WorkerSandbox.onMessage (file:///Users/meain/dev/src/silverbullet/lib/plugos/sandboxes/worker_sandbox.ts:93:30)
    at Worker.worker.onmessage (file:///Users/meain/dev/src/silverbullet/lib/plugos/sandboxes/worker_sandbox.ts:59:14)
    at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at Worker.#pollMessages (ext:runtime/11_workers.js:253:12)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

**Comment by meain** [comment]
Could it be related to https://github.com/silverbulletmd/silverbullet/issues/990 ?

**Comment by zefhemel** [comment]
Could you try uninstalling the ai plug and see if that changes anything?

**Comment by justyns** [comment]
Can you try setting `embeddingModels: []` in the ai section of your settings and see if that error goes away?

I'll take a look at the code later today dor a better fix, but I'm assuming it's trying to read that and can't

**Comment by meain** [comment]
@zefhemel removing the ai plug did not seem to help, well kinda. I have 8 decorations in my SETTINGS, once of which is to hide toc for my index page. That one does seem to work, but none of the others do(not even the ones I have directly added in a page). I btw do see `Loaded 8 object decorators` in the server logs.

@justyns I was getting the error even with `embeddingModels: []` added under `ai:`.

**Comment by meain** [comment]
Interestingly, after all this experimentation it stopped working even in online mode on my phone.

**Comment by zefhemel** [comment]
What decorators did you define?

**Comment by meain** [comment]
```yaml
objectDecorators:
- where: "tags = 'person'"
  attributes:
    pageDecoration.prefix: '"🧑 "'
- where: "tags = 'family'"
  attributes:
    pageDecoration.prefix: '"👨‍👩‍👧‍👦 "'
- where: "tags = 'video'"
  attributes:
    pageDecoration.prefix: '"📹 "'
- where: "name =~ /Journal\\/Day\\/*/"
  attributes:
    pageDecoration.prefix: '"🗓️ "'
- where: "name =~ /Backlog\\/*/"
  attributes:
    pageDecoration.prefix: '"✅ "'
- where: "name = 'home'"
  attributes:
   pageDecoration.disableTOC: "true"
- where: 'tags = "notoc"'
  attributes:
     pageDecoration.disableTOC: "true"
- where: "tags = 'hidden'"
  attributes:
    pageDecoration.hide: "true"
```
