### ISSUE TITLE
Incorrect parsing using YAML.parse

### ISSUE THREAD

**Issue by Ben7on** [silverbulletmd/silverbullet#1111]
It seems the YAML.parse syscall is not parsing the `attribute.subAttribute` notation correctly.

For example, see the following frontmatter and corresponding parsed object

```yaml
tags: template
displayName: "Test"
hooks:
  newPage:
    suggestedName: "Test"
```
```json
{
  "tags": "template",
  "displayName": "Test",
  "hooks": {
    "newPage": {
      "suggestedName": "Test"
    }
  }
}
```
```yaml
tags: template
displayName: "Test"
hooks.newPage:
    suggestedName: "Test"
```
```json
{
  "tags": "template",
  "displayName": "Test",
  "hooks.newPage": {
    "suggestedName": "Test"
  }
}
```

In the second example, this leads to `TypeError: frontmatterYaml.hooks is undefined` when trying to access `frontmatterYaml.hooks.newPage.suggestedName`.
