### ISSUE TITLE
Add configuration for smart quotes

### ISSUE THREAD

**Issue by majjejjam** [silverbulletmd/silverbullet#1114]
First of all, thank you for this wonderful program! It's been a joy to use. On to the issue:

It's common for non-English languages to use quotation marks different from the English ones. For example, in German, you would usually quote like this:

„Hast“

In French, like this:

« mot »

And so on. It would be useful if there was a setting to configure custom left and right quotation marks when using smart quotes.

**Comment by Maarrk** [comment]
I have recently contributed a very similar feature #960, the actual code to set the characters is here:
https://github.com/silverbulletmd/silverbullet/blob/4b6cd183a82e18df864347f813615cc5f7c2b823/web/cm_plugins/smart_quotes.ts#L88-L91

I can make the PR, but how would we want the configuration to look like? To keep it backwards compatible, I imagine something like this for your German example:
```yaml
# Toggles between “smart” ‘quotes’ (left and right) and "simple" 'quotes' (good ol' ASCII)
useSmartQuotes: true
# Assign different characters for smart quotes
smartQuotes:
  single:
    left: "‚"
    right: "’"
  double:
    left: "„"
    right: "”"
```

It does look a bit verbose, but I think it's better like this than `smartQuotes: [ "‚", "’", "„", "”" ]` 😄 

And `useSmartQuotes` feels like it could be `smartQuotes.use` in for nicer structure if there's more. Maybe change it, but make the code support the old version as well? (just don't show it in the SETTINGS page on silverbullet.md anymore)
