### ISSUE TITLE
Request to Bypass Silverbullet Built-in Login When Using External Authentication

### ISSUE THREAD

**Issue by simone-viozzi** [silverbulletmd/silverbullet#1123]
Hi,

I have Traefik with Authelia in front of Silverbullet, and I would like to disable the built-in authentication in Silverbullet, leaving the authentication entirely in the hands of Authelia.

Here is my current configuration for Silverbullet:

```yaml
services:
  silverbullet:
    image: zefhemel/silverbullet
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SB_USER=admin:admin
      - PUID=1000
      - GUID=1000
    volumes:
      - silverbullet-space:/space
    ports:
      - 4678:3000
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy

      traefik.http.routers.silverbullet.rule: Host(`${SILVERBULLET_DOMAIN}`)
      traefik.http.routers.silverbullet.entrypoints: websecure

      traefik.http.routers.silverbullet.tls: "true"
      traefik.http.routers.silverbullet.tls.certresolver: leresolver

      traefik.http.routers.silverbullet.service: silverbullet-svc
      traefik.http.services.silverbullet-svc.loadbalancer.server.port: "3000"

      traefik.http.routers.silverbullet.middlewares: authelia@docker
    networks:
      - proxy
    logging:
      driver: "local"
```

And here is the relevant part of my Authelia configuration:

```yaml
    - domain: silverbullet.yourdomain.com
      resources:
        - '/.client/manifest.json$'
        - '/.client/[a-zA-Z0-9_-]+.png$'
        - '/service_worker.js$'
      policy: bypass

    - domain: silverbullet.yourdomain.com
      policy: one_factor
      subject:
        - group:users
```

Despite having Authelia set up as the authentication middleware in front of Silverbullet, I am still being prompted by Silverbullet's own login page after authenticating through Authelia. 

Currently, the Silverbullet login is set to `admin:admin`, but I want to bypass this completely and let Authelia handle all authentication.

Is there a way to fully disable the built-in Silverbullet authentication or an alternative method to achieve this behavior?

Any help or guidance would be greatly appreciated.

Thank you
