### ISSUE TITLE
Page slowdown with long file path

### ISSUE THREAD

**Issue by jaaacck** [silverbulletmd/silverbullet#1180]
I seem to get slowdown and characters replaced when I have the page Opener/creator (Cmd+K) open and typing a file name.
Example file name: "technical/fortinet/fortiswitch/example".

The issue seems to happen when the file name gets longer. Apologies but it's hard to explain in text, please see the video below - https://www.youtube.com/watch?v=v5otwQ6Vpzo.

I'm running this on docker. Storage is local to where the docker container is running. 
Here's my compose file, it's pulled through v0.10.1
```yaml
version: "3.9"
services:
  silverbullet:
    image: zefhemel/silverbullet
    restart: unless-stopped
    environment:
    - SB_USER=jack:<removed>
    volumes:
      - /mnt/user/appdata/silverbullet/space:/space
    networks:
      - nginx_web

networks:
  nginx_web:
    external: true  
```

I am going via a reverse proxy to do SSL offloading. 
This is happening across different hardware and browsers. I've confirmed on Windows 10, 11 on Chrome and Firefox. I've also confirmed on Mac Sonoma 14.4.1 (23E224) with Firefox and Safari.

There's nothing in my logs other than the below which isn't being spammed or repeated, maybe once per minute

```
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
silverbullet-1  | Requested file index.md
```

My instance is quite small with 290 files and a DB size of 40M:

```
jack@nas:/mnt/user/appdata/silverbullet/space# find . -type f | wc -l
290

jack@nas:/mnt/user/appdata/silverbullet/space# du -sh .*
40M	.silverbullet.db
32K	.silverbullet.db-shm
5.0M	.silverbullet.db-wal
```
