### ISSUE TITLE
embedding width

### ISSUE THREAD

**Issue by tribor** [silverbulletmd/silverbullet#1197]
I have set the width to `200`. however, this is not taken into account

**silverbullet  version**: 0.10.1
**browser**: Firefox 133.0.3 + Chrome 131.0.6778.205 

**content**:
```
start
```embed
url: https://example.com
width: 200
height: 400
```
**screenshot**:
![width-bug](https://github.com/user-attachments/assets/3f3f4cfa-e616-496e-ad9e-3158655462ad)

**debug**:
```yaml
type: Document
from: 0
to: 66
children:
  - type: Paragraph
    from: 0
    to: 5
    children:
      - from: 0
        to: 5
        text: start
  - from: 5
    to: 6
    text:2+
  - type: FencedCode
    from: 6
    to: 66
    children:
      - type: CodeMark
        from: 6
        to: 9
        children:
          - from: 6
            to: 9
            text: '```'
      - type: CodeInfo
        from: 9
        to: 14
        children:
          - from: 9
            to: 14
            text: embed
      - from: 14
        to: 15
        text:2+
      - type: CodeText
        from: 15
        to: 62
        children:
          - from: 15
            to: 62
            text: |-
              url: https://example.com
              width: 200
              height: 400
      - from: 62
        to: 63
        text:2+
      - type: CodeMark
        from: 63
        to: 66
        children:
          - from: 63
            to: 66
            text: '```'
```
