### ISSUE TITLE
Add data attributes to tables

### ISSUE THREAD

**Issue by mjf** [silverbulletmd/silverbullet#1207]
Please add [data attributes](https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Solve_HTML_problems/Use_data_attributes) to all tables (everywhere where HTML tables are rendered, escpecially the [`<td>` data attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td) element (*e.g.*, `data-label="<column name>"`).  Responsive tables could then be *fairly easy* to implement using only *CSS*.

<details><summary>Simplest example</summary>

```css
@media screen and (max-width: 800px) {
  table thead {
    visibility: hidden;
  }
  table tr,
  table td {
    display: block;
  }
  table td::before {
    content: attr(data-label)': '; /* Cool what we can do today! */
    float: left;
  }
}
```

I tested the above from `space-style` and it works, except that there is no *data attribute* to be used now, so the attribute hack has of course no effect. I'd really like to see this minor change implemented. It will make life on mobile easier.
</details>
