### ISSUE TITLE
`data-tag-name` not applied in HTML

### ISSUE THREAD

**Issue by nucleogenesis** [silverbulletmd/silverbullet#1208]
I'm trying to customize the appearance of particular tags per the suggestion in the docs:

```css
/* --> Example Tag with angle brackets: #<my cool tag> */
.sb-hashtag[data-tag-name="my cool tag"] {
  background: purple;
  color: limegreen;
  font-weight: bolder;
}
```

But when I make a line `#hello there` in a doc, then inspect that element, this is the HTML output:

```html
<div class="cm-line"><span class="sb-hashtag">#hello</span> there</div>
```

So there is no effect if I put space-styles like, for example:

```css
.sb-hashtag[data-tag-name="hello"] { 
    background: orange;
    color: purple; 
}
```

I may investigate in the code a bit when/if I have time, so any guidance would be appreciated.

Running Version: 0.10.1 on Fedora Linux in Chromium browser

I _do_ wonder, though, if this is something only I am experiencing because it seems like a bug that would affect people pretty immediately for anybody using such custom space-styles - so I'm curious if you/anybody can replicate.
