### ISSUE TITLE
Markdown checklists should not show bullets

### ISSUE THREAD

**Issue by damufo** [silverbulletmd/silverbullet#1223]
The current markdown preview render is showing bullets:

 - [x] checked list item
 - [ ] unchecked list item

↓↓↓

![Image](https://github.com/user-attachments/assets/3add4ffe-34e3-48df-9f11-473bf11516b6)

The bullets are hidden in most implementations, including GitHub, which is the original.

**Comment by zefhemel** [comment]
Interesting. However I often mix regular and task items in bulleted lists. That would look odd then, or there would have to be a special case for bulleted lists with just tasks.

**Comment by damufo** [comment]
github implementation

- [ ] item one
- [ ]  item two
- item three
- [ ] item four
- item five

When no task show bullet.

**Comment by kolmone** [comment]
Github seems to show a bulleted task with the syntax `- - [ ]` or `* * [ ]`

- [ ] task with `- [ ]`
- - [ ] task with `- - [ ]`
- regular bulleted item

**Comment by damufo** [comment]
- [ ] item
-  - [ ] item2
* [ ] Iem 3 
* *  [ ] Item 4

```
- [ ] item
-  - [ ] item2
* [ ] Iem 3 
* *  [ ] Item 4

**Comment by zefhemel** [comment]
Sadly with the way CodeMirror generates HTML this may not be that easy to perfectly align, but worth a shot.

**Comment by KitAmbraid** [comment]
Hey there, here's a bit of css that fixes it, you can add it as a `space-style` block.
Notes:
- you can play with the `--editor-indent-multiplier` theme variable to find the spacing that works best for you
- depending on your font, the bullet points might not be perfectly aligned with the checkboxes: tinker with the `--li-touchup` var to find your proper setting

```css
/* Scoping on lists */
@scope (#sb-main .cm-editor .sb-line-ul.sb-line-li-1) {
  & { 
    --li-touchup: -8px;

    --base-indent: calc(3ch * var(--editor-indent-multiplier));
    --depth: 1;
  }
  &.sb-line-li-2 { --depth: 2; }
  &.sb-line-li-2.sb-line-li-3 { --depth: 3; }
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4 { --depth: 4; }
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 { --depth: 5; }

  & .cm-list-bullet::after,
  &.sb-line-li-2 .cm-list-bullet::after,
  &.sb-line-li-2.sb-line-li-3 .cm-list-bullet::after,
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4 .cm-list-bullet::after,
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 .cm-list-bullet::after {
    width: var(--base-indent);
    min-width: var(--base-indent);
    text-align: center;
    text-indent: 0;
    display: inline-block;
    position: relative;
    left: 0;
    margin-left: var(--li-touchup);
  }

  &,
  &.sb-line-li-2,
  &.sb-line-li-2.sb-line-li-3,
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4,
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 {
    padding-left: calc(var(--base-indent) * (calc(var(--depth) - 1)));
    text-indent: 0;
  }

  
  & .sb-list:first-child,
  &.sb-line-li-2 .sb-list:first-child,
  &.sb-line-li-2.sb-line-li-3 .sb-list:first-child,
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4 .sb-list:first-child,
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 .sb-list:first-child { 
    display: none; 
  }

  /* Scoping on tasks */
  @scope (&.sb-line-task) {
    &,
    &.sb-line-li-2,
    &.sb-line-li-2.sb-line-li-3,
    &.sb-line-li-2.sb-line-li-3.sb-line-li-4,
    &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 {
      text-indent: 0;
      padding-left: calc(var(--base-indent) * (calc(var(--depth) - 1)));
    }
    
    & .cm-list-bullet::after,
    &.sb-line-li-2 .cm-list-bullet::after,
    &.sb-line-li-2.sb-line-li-3 .cm-list-bullet::after,
    &.sb-line-li-2.sb-line-li-3.sb-line-li-4 .cm-list-bullet::after,
    &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 .cm-list-bullet::after { 
      display: none; 
    }

    
    & .sb-checkbox {
      width: var(--base-indent);
      min-width: var(--base-indent);
      text-align: center;
      display: inline-block;
      text-indent: initial;
    }

    & .sb-list:not(.sb-task),
    & .cm-list-bullet {
      display: none;
    }
    
    /* task when cursor is next to that part: - [ ] */
    @scope (&:has(.sb-task-state)) {
      & .sb-list,
      & .cm-list-bullet {
        display: inline;
        visibility: visible;
      }
    }
  }
}
```

What it looks like with my settings:

![Image](https://github.com/user-attachments/assets/ee697f2c-1da0-4cc8-ad61-da2ac82244f7)

I may or may not write down a proper PR, may or may not have the time & energy some day soonish, so anyone wanting to do it instead please leave a comment so that I know you're on it.

**Comment by damufo** [comment]
@KitAmbraid

I'm not requesting support, I'm just commenting on the case in case any corrections need to be made to the CSS.

I add your css for my space-style SETTINGS but not work for me.

![Image](https://github.com/user-attachments/assets/912df103-23dc-4fd5-8b28-5d843b446a06)

I reload system and user interface.

Result:

![Image](https://github.com/user-attachments/assets/9117f206-60ca-4ea4-a101-414980c705fa)

**Comment by zefhemel** [comment]
This is cool. If somebody's willing to merge this into the main code base and issue a PR I'd appreciate it a lot 😄

**Comment by Rokainu-Codes** [comment]
I tried this out and noticed that text started disappearing when I removed a task or list bullet. I adjusted the scope of the space-style snippet to correct that. 

```css
/* Scoping on lists */
/* :has(.cm-list-bullet) selector makes sure adjustments only apply to lines that usually have a list bullet */
@scope (#sb-main .cm-editor .sb-line-ul.sb-line-li-1) {
  & { 
    --li-touchup: -1ch;
    --editor-indent-multiplier: 1;
    --base-indent: calc(2ch * var(--editor-indent-multiplier));
    --depth: 1;
  }

  &.sb-line-li-2 { --depth: 2; }
  &.sb-line-li-2.sb-line-li-3 { --depth: 3; }
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4 { --depth: 4; }
  &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5 { --depth: 5; }
  & { --depth-adjusted-indent: calc(calc(var(--base-indent) - 2ch) * (calc(var(--depth) - 1)));}
  @scope (&:has(.cm-list-bullet)) {
    @scope (
      &,
      &.sb-line-li-2,
      &.sb-line-li-2.sb-line-li-3,
      &.sb-line-li-2.sb-line-li-3.sb-line-li-4,
      &.sb-line-li-2.sb-line-li-3.sb-line-li-4.sb-line-li-5
    ) {
      & {
        padding-left: var(--depth-adjusted-indent);
        text-indent: 0;
      }
  
      & .cm-list-bullet::after {
        width: var(--base-indent);
        min-width: var(--base-indent);
        text-align: center;
        text-indent: 0;
        display: inline-block;
        position: relative;
        left: 0;
        margin-left: var(--li-touchup);
      }
  
      & > .sb-list:first-child { display: inline; }
      & > .sb-li-cursor .sb-list.sb-meta { display: inline; }
  
      /* Scoping on tasks */
      @scope (&.sb-line-task) {
        & {
          text-indent: 0px;
          padding-left: var(--depth-adjusted-indent);
        }
        
        & .cm-list-bullet::after { 
          display: none; 
        }
    
        
        & .sb-checkbox {
          width: var(--base-indent);
          min-width: var(--base-indent);
          text-align: center;
          display: inline-block;
          text-indent: initial;
        }

        & .sb-checkbox > input[type=checkbox] {
          width: var(--base-indent);
        }
    
        & .sb-list:has(~ .sb-checkbox),
        & .cm-list-bullet {
          display: none;
        }
        & > .sb-list:first-child { display: inline; }
        & .cm-task-checked .sb-list.sb-task { display: inline; }
      }
    }
  }
  /* Adding additional indentation to list items where the list bullet has been removed */
 @scope (&:not(:has(.cm-list-bullet))) {
    @scope (&:not(:has(.sb-list.sb-task))){
      & > .sb-list:first-child { 
        padding-left: calc(calc(calc(var(--base-indent) - 2ch) * var(--depth)) + 1ch);
      }
    }
  }
}
```
