### ISSUE TITLE
Add `hook.afterFrontMatter`

### ISSUE THREAD

**Issue by mjf** [silverbulletmd/silverbullet#1238]
Add `hook.afterFrontMatter` to appear between front matter and page content. Maybe better naming can be `hook.frontMatterBottom`.

Usecase: I would like to see breadcrumbs after front matter, e.g.,

```yaml
description: Add breadcrumbs right after the page front matter
tags:
  - template
hooks.afterFrontMatter:
  where: |
    parent != 'builtin' and name !=~ /^[📌🔍]/ and tags != 'meta' and tags != 'template'
  order: -5
---
### ${breadcrumbs()}
```

When moving up and down with the caret, it will jump over the template generated content into the frontmatter and back to the page content. Is it achievable?
