### ISSUE TITLE
Is inline space lua suppose to work on Page templates?

### ISSUE THREAD

**Issue by jinder1s** [silverbulletmd/silverbullet#1274]
I am using the following frontmatter for a page template and I want the suggested name to be based on output of a space lua function. Is that supported currently??

```
---
tags: template
description: "Create a new page"
displayName: ""
hooks.newPage:
  suggestedName: "${os.date('%Y%m%d%H%M%S')}"
  command: "New Page"
---
```
