### ISSUE TITLE
Doesn't run if space folder is bound to an SMB mounted volume

### ISSUE THREAD

**Issue by rom1henry** [silverbulletmd/silverbullet#1314]
Hi!
I'm trying to install SB on an unprivileged Alpine-docker LXC on Proxmox. I have mounted a volume from a Synology NAS to the PVE host, and passed the mount to the LXC in `/srv/smbshare`.  See compose file below

```
services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    restart: unless-stopped
    environment:
    - SB_USER=admin:********
    volumes:
      - /srv/smbshare/silverbullet/space:/space
    ports:
      - 3000:3000
  # To enable auto upgrades, run watchtower
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

After starting the container, only the `.silverbullet.db` file is created in `/srv/smbshare/silverbullet/space` (but is 0B). Logs below. Am I doing something obviously wrong? Thanks for your help!

```
Will run SilverBullet with UID 0, inferred from the owner of /space (set PUID environment variable to override)
Unhandled rejection: PromiseRejectionEvent {
  bubbles: false,
  cancelable: true,
  composed: false,
  currentTarget: Window {},
  defaultPrevented: false,
  eventPhase: 2,
  srcElement: null,
  target: Window {},
  returnValue: true,
  timeStamp: 0,
  type: "unhandledrejection",
  promise: Promise {
    <rejected> Error: database is locked
    at async Object.openKv (ext:deno_kv/01_db.ts:10:15)
    at async tx (file:///silverbullet.js:140:14735971)
    at async U.NH [as actionHandler] (file:///silverbullet.js:140:14737513)
    at async U.execute (file:///silverbullet.js:24:8738)
    at async U.parseCommand (file:///silverbullet.js:24:6451)
    at async file:///silverbullet.js:188:7166
  },
  reason: Error: database is locked
    at async Object.openKv (ext:deno_kv/01_db.ts:10:15)
    at async tx (file:///silverbullet.js:140:14735971)
    at async U.NH [as actionHandler] (file:///silverbullet.js:140:14737513)
    at async U.execute (file:///silverbullet.js:24:8738)
    at async U.parseCommand (file:///silverbullet.js:24:6451)
    at async file:///silverbullet.js:188:7166
}
```
