### ISSUE TITLE
VIM mode cursor blink

### ISSUE THREAD

**Issue by marendowski** [silverbulletmd/silverbullet#1345]
Hi, is there a way to change the cursor to not blink while in VIM mode (or permanently)?

Cheers

**Comment by zefhemel** [comment]
I don't think so. If so, it'd need to be added to https://github.com/replit/codemirror-vim upstream, then I can enable/support it in SB as well.

**Comment by maxrichter-dyna** [comment]
You can disable the blinking with this `space-style` snippet:
```css
/*Disable vim mode cursor blinking*/
.cm-vimCursorLayer {
    animation: none !important
}
```
