### ISSUE TITLE
Change keyboard shortcuts?

### ISSUE THREAD

**Issue by NoLooseEnds** [silverbulletmd/silverbullet#193]
Is there any way to change the keyboard shortcuts by changing the config? I'm on a Norwegian keyboard, and our `/`-key is "hidden" behind `shift + 7`. Using `cmd + shift + 7` does not work, so I'm forced using the mouse to click which influences the workflow in a negative way.

![image](https://user-images.githubusercontent.com/4103531/207343128-1cf9dfbb-d14f-45da-aded-b541722dd938.png)

Bonus question:
Is there possible to change the default font in the config, without overriding the CSS?

**Comment by zefhemel** [comment]
The answer to both of these for now is: no, not yet possible.

Regarding keyboard mappings: yeah, this is something I know we need to support at some point. I’m open to how to configure this though. Perhaps it would make sense to put this in YAML format in `SETTINGS` something along the lines of:

```yaml
keys:
  “Command Palette”:
    mac: “Cmd-p”
    key: “Ctrl-p”
  “Page: Rename”:
    mac: “Cmd-r”
    # etc.
```

Command patte would have to be a special case because it’s not a command itself. Another approach would be to mirror the struction of plug files but then allow specific overrides. This would be more flexible (you could override various other things), but probably harder to use, e.g.:

```yaml
overrides:
   core:
      renamePage:
        command:
            mac: “Cmd-r”
```

Basically this way, we’d merge whatever you keep under `overrides` and then the plug name (e.g. `core`) with what it pulls from e.g. https://github.com/silverbulletmd/silverbullet/blob/main/plugs/core/core.plug.yaml allowing you to override arbitrary attributes. This way you could also rename commands for instance, or even define basic new ones.

Regarding overriding fonts: also not possible right now. There’s a discussion on theming here, it just needs to be picked up: https://github.com/silverbulletmd/silverbullet/discussions/58 For now a lot of the lay-out working relies on monspaced fonts, so that will likely remain a restriction for some time.
