### ISSUE TITLE
Eliminate vertical jumping

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#208]
When moving the cursor (by keyboard or mouse), a lot of vertical jumping happens around certain areas:

* [x] Frontmatter
* [x] Directives
* [x] Fenced code blocks

This is highly distracting, and sometimes leads to surprising results, like following links that jump “under” the cursor. While I think it’s visually clean to hide some of the markdown clutter, this vertical space should still be there in order to avoid this type of jumping.

**Comment by zefhemel** [comment]
Here is an example for fenced code blocks:

https://user-images.githubusercontent.com/59073/208165010-00a0b0b0-fd84-498e-b575-4e153a0874d5.mov

**Comment by zefhemel** [comment]
And directives


https://user-images.githubusercontent.com/59073/208165295-d420c8d3-2d4e-4ba0-8f8f-564b787b0ceb.mov

**Comment by zefhemel** [comment]
Should be much better now, these element will always take up more vertical space though. Open to styling improvements.

**Comment by jdiercks** [comment]
So far I'm willing to accept the jumpiness, we'll see if the click-misfire risks eventually convince me otherwise, but at least with STYLES we can choose. I even took it to the extreme with this, which visually I really like:

```css
/* collapse query/code block wrappers when hidden */
.sb-directive-start-outside, 
.sb-directive-end-outside, 
.sb-line-code-outside {
  white-space: nowrap;
  overflow: hidden;
  pointer-events: none;
  height: 1px;
}

```
