### ISSUE TITLE
Make plugs more explicitly define settings

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#226]
Right now various plugs implicitly read values from `SETTINGS` possibly documenting them, possibly not. It would be nicer if plugs can explicitly define their settings as well as their schema (at least their type). Same for `SECRETS` I suppose.

Not only is this better for documentation, it would also enable building a automatically generated proper settings UI listing all settings, changing them etc. Something more intuitive than YAML in a page.

Not sure how this should be specified yet, one way would be to extend the `.plug.yaml` format at the PlugOS level, something along the lines of:

```yaml
name: core
settings:
  initPage:
    type: string
    default: index
    description: Specifies the first page to load when loading your space
  weeklyNoteTemplate:
    type: string
    default: template/Weekly Note
functions:
    # …
```
