### ISSUE TITLE
Add file watching support for plugs

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#250]
Allow plugs to listen for file changes (e.g. using the OS' native file watching support). This would open a few use cases:

* Automatic reindexing of pages edited outside of SB
* Plugs that interact or implement background syncing

If fully reliable, this could replace the "on save" event listening for reindexing and purely rely on file watching.

Implementation details to figure out:

* Should this be built on top of OS-level primitives (e.g. [watchFs](https://deno.land/api@v1.29.1?s=Deno.watchFs)) or at the "space" level by somehow polling all paths inside of a watched namespace (this could be prohibitively expensive) — the latter would also allow detecting of changes in "virtual" parts of the space, e.g. remotely mounted pages.

How to specify:

```yaml
functions:
  fsWatcher:
    path: ./watcher.ts:watch
    watchPrefix:
    - "" # To watch for the entire space
    - syncme/ # To watch with a prefix
```

Alternatively, if these prefixes need to be dynamically settable (e.g. via `SETTINGS`), then perhaps this needs to be done via syscalls instead, e.g. `system.watchFs("syncme/*", "syncme-file-changed")` (where the first one is a prefix to watch, and the second argument the event to trigger once this happens), as well as a `system.unWatchFs` to unsubscribe. These subscriptions would have to be tied to the specific plug, and dynamically unregistered when a plug un/reloads.
