### ISSUE TITLE
[Desktop] Allow commands to extend native menus

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#272]
Conceptually:

```yaml
functions:
  myCommand:
    path: file.ts:myCommand
    command:
      name: “My Command”
      menu: “My Menu > My Command”
      key: “Ctrl-Shift-c”
```

This would create a “My Menu” top level menu, with a “My Command” menu item triggering `myCommand` on click (but the keyboard shortcut would also work).
