### ISSUE TITLE
Exclude frontmatter when #include page

### ISSUE THREAD

**Issue by thecandlestick** [silverbulletmd/silverbullet#416]
Perhaps making it a configurable setting, but by default most frontmatter is relevant only to the page itself and only serves to clutter other pages.

---

NOTE: temporary fix provided by Alan3672647383

add to STYLES
```css
.sb-frontmatter{
    display: none !important;
}
```
to hide frontmatter everywhere
