### ISSUE TITLE
problems with enabling user/password authentication. does not work.

### ISSUE THREAD

**Issue by uGeek** [silverbulletmd/silverbullet#419]
I have tried with the docker compose uncomment to enable authentication by user and password and it doesn't work.

From what I've seen, to use the user=angel password=1234 add this in the docker-compose? 

command: ["--user=angel:1234"]

```
  silverbullet:
    image: zefhemel/silverbullet
    container_name: silverbullet
    ## To enable additional options, such as BasicAuth, uncomment the following line:
    command: ["--user=angel:1234"] 
    volumes:
      - ./space:/space
    ports:
      - 3000:3000
```
