### ISSUE TITLE
Hidden text is still interactable

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#424]
Some text is hidden from the user when not in edit mode, such as the queries. They are still clickable though. I have numerous times had a link in a query, which when clicked (while not visible), navigates me there, which was not the intention.

This could be fixed by using the following css rule:

```css
  .sb-directive-start-outside {
    pointer-events: none;
  }
```
