### ISSUE TITLE
Query blocks take up a lot of visual realestate 

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#425]
When the query blocks are not being edited, they still render the text inside of them, which makes them take up a lot of space. For more complicated queries, this can be quite a few lines. I propose that they are collapsed/hidden when not being edited. I have personally applied the following css rule to mitigate this issue on my end:

```css
  .sb-directive-start-outside {
    white-space: nowrap;
    overflow: hidden;
    pointer-events: none;
  }
```
