### ISSUE TITLE
PWA Authentication Issues

### ISSUE THREAD

**Issue by itsallyours** [silverbulletmd/silverbullet#482]
I absolutely love the PWA.  It solves so many problems for me.

However, I occasionally get a problem where my edits from one device do not show up with another.  Ultimately, I have to go into the config of the application (via Edge) and delete the cookies for the broken client.  Go back to PWA instance and reauthenticate.  After reauth, it works great (for a while).

Today, this happened and lost all of my edits from the last 24 hours  (this is the 3rd time with data loss).

Basic setup:
- Docker
- NGINXProxyManager
- Authelia (using https://silverbullet.md/Authelia for reference).

It's almost like the background updater is getting 401's and never bubbles it up to the UI.  (just my theory)

A couple random thoughts/questions:
- Is there a way to show server status (online/offline)?
- Any way to preserve changes in this use case?

Let me know if I am misinterpreting something...happy to trace with some guidance.

**Comment by itsallyours** [comment]
for clarity:  this is not a case where conflict files were created.  They changes (new files) were just lost.

**Comment by itsallyours** [comment]
another thought...I updated the server version but the client version was behind (it didn't have the reset client command).  maybe this was root cause?

**Comment by zefhemel** [comment]
We've been struggling to get everything to work properly with Authelia for a while now, and I thought we were in a good place. But apparently not (or

**Comment by itsallyours** [comment]
I didn't know about the gray vs. yellow.   That is very helpful going forward.

Right now, it just happened again.  It was yellow.

I deleted auth cookie and it seemed to correct itself after reauth.

With my iPhone, I am not sure how to clear the cookies with the PWA (safari).   It is currently yellow.  

Also, how do you unregister the service worker?

**Comment by itsallyours** [comment]
I have browser right now that I have left alone with the issue.
![image](https://github.com/silverbulletmd/silverbullet/assets/6984512/8abdb155-1c35-484e-ac22-636bc8a37387)

what is interesting is that the failing requests do not have any cookies on them.
![image](https://github.com/silverbulletmd/silverbullet/assets/6984512/91ce8178-038c-467c-a020-023161aaf000)

I can do a CRTRL F5 and still no prompt to authenticate.  If I go to new incognito window, it works just fine with the auth prompt, etc.

**Comment by zefhemel** [comment]
What I would really like to know is the HTTP status code you're getting back for those requests. Can't see that from the screenshot.

**Comment by itsallyours** [comment]
on the broken one:
no response.  ns_error_interception_failed

on a new private window:
request against / returns a 302 to the authelia login page.

**Comment by zefhemel** [comment]
Strange. And the URL the request is not another domain, right? Can I see the URL?

You're using Firefox here right, I'm wondering if you see the same behavior with a chromium based browser or safari.

**Comment by itsallyours** [comment]
I did some additional debugging.  I get the same behavior with Chrome and Edge.

With Chrome, I ran this test:

1. Logged in
2. let everything to download in the browser
3. deleted the cookie
4. banner turned yellow
5. most things were 200 served by service worker.  A few items were 302 (redirects to login).
6. ctrl F5 refresh got it back to login page.

I looked at authelia logs.  Everything was being returned to NGINX Proxy Manager as 401.  NPM was converting 401 to 302 with a return url.

I think fundamentally the issue was cookies were expiring and nothing was sending the browser back to the login page.

I have a HAR log of the above.  If you want it, I can email you a link (don't want to post it).

**Comment by zefhemel** [comment]
Yes please zef@zef.me

**Comment by paletochen** [comment]
Hi,
I have a similar setup as OP:


 - Docker
 - NGINXProxyManager
 - Authelia

If it helps, here are all my config details:

**Values used for this example:**
- Internal network: 192.168.1.X
- IP from my server hosting Silverbullet + Authelia + NPM: **192.168.1.9**
- Personal domain: **domain.com**
- Silverbullet subdomain: **pkms.domain.com**
- Auth subdomain: **auth.domain.com**
- domain.com, pkms.domain.com and auth.domain.com redirect all to my public IP
- SilverBullet : **192.168.1.9:3000**
- Authelia: **192.168.1.9:9091**
- NPM: **192.168.1.9:81**
- Ports 80 and 443 needs to be opened in your router firewall

## Docker compose
```yml
services: 
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' 
      - '81:81'
      - '443:443'
    volumes:
      - /media/docker/nginx/config/config.json:/app/config/production.json
      - /media/docker/nginx/data:/data
      - /media/docker/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - proxydb
    networks:
      - nginx-proxy

  proxydb:
    image: 'yobasystems/alpine-mariadb:latest'
    container_name: proxy-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'PASSWORD'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'David'
      MYSQL_PASSWORD: 'PASSWORD'
    volumes:
      - /media/docker/mariadb/data/mysql:/var/lib/mysql
    networks:
      - nginx-proxy

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /media/docker/authelia/config:/config
    ports:
      - 9091:9091
    networks:
      - nginx-proxy
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - PUID=1000
      - PGID=1000


  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    restart: always
    networks:
      - nginx-proxy
    tmpfs:
    - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  nginx-proxy:
    name: nginx-proxy
```

## Authelia configuration.yml

```yml
###############################################################################
#                           Authelia Configuration                            #
###############################################################################
theme: dark
jwt_secret: sdf33df845ddsfsf6g8sds8f7gs89g7680g
default_redirection_url: https://auth.domain.com/

##
## Server Configuration
##
server:
  host: 0.0.0.0
  port: 9091
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

  tls:
    key: ""
    certificate: ""
    client_certificates: []


##
## Log Configuration
##
log:
  level: debug


##
## TOTP Configuration
##
totp:
  disable: false
  issuer: domain.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

##
## WebAuthn Configuration
##
webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

##
## NTP Configuration
##
ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

##
## Password Policy Configuration.
##
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

##
## Access Control Configuration
##
access_control:
  default_policy: deny

  rules:
    - domain: 'auth.domain.com' #This should be your authentication URL
      policy: bypass
    - domain: 'pkms.domain.com'
      resources:
        - '/.client/manifest.json$'
        - '/.client/[a-zA-Z0-9_-]+.png$'
        - '/service_worker.js$'
      policy: bypass
    - domain: 'pkms.domain.com'
      policy: two_factor

##
## Session Provider Configuration
##
session:
  name: authelia_session
  domain: domain.com
  same_site: lax
  secret: hjkghj25ghgt2kj5thgk24j5gh
  expiration: 6h
  inactivity: 5h
  remember_me_duration: 24h

##
## Regulation Configuration
##
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

##
## Storage Provider Configuration
##
storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: safsdfasf34qwrt2f2v

##
## Notification Provider
##
notifier:
  disable_startup_check: true #true/false
  smtp:
    username: email@gmail.com #your email address
    password: sdffdf232r3fdsf #your email password
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port
    sender: email@gmail.com
    subject: "[Authelia] {title}" #email subject
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: smtp.gmail.com
      skip_verify: false
      minimum_version: TLS1.2
...
```

## Nginx Proxy Manager

### auth.domain.com

**Details**
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/e20d1f4f-ae60-403d-b06a-ee2e49a22ab3)

**SSL**
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/ac74293a-6133-4434-aac4-609e8bbeb0e7)

**Advanced**

```
location / {
        set $upstream_authelia http://192.168.1.9:9091; # e.g. http://192.168.1.13:9091 
        proxy_pass $upstream_authelia;
        client_body_buffer_size 128k;

        #Timeout if the real server is dead
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

        # Advanced Proxy Config
        send_timeout 5m;
        proxy_read_timeout 360;
        proxy_send_timeout 360;
        proxy_connect_timeout 360;

        # Basic Proxy Config
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_redirect  http://  $scheme://;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_cache_bypass $cookie_session;
        proxy_no_cache $cookie_session;
        proxy_buffers 64 256k;

        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods *;
        add_header Access-Control-Allow-Headers x-sync-mode;

        # If behind reverse proxy, forwards the correct IP
        set_real_ip_from 192.168.0.0/16;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
    }
```

### pkms.domain.com

**Details**
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/83f638f3-86b6-4f01-8332-55399ee27cb3)

**SSL**
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/34a80453-7bbc-4243-ae8a-f49975278148)

**Advanced**
```
location /authelia {
    internal;
    set $upstream_authelia http://192.168.1.9:9091/api/verify; #ADD YOUR IP AND PORT OF AUTHELIA
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr; 
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods *;
    add_header Access-Control-Allow-Headers x-sync-mode;

    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}

    location / {
        set $upstream_pkms http://192.168.1.9:3000;  #ADD IP AND PORT OF SERVICE
        proxy_pass $upstream_pkms;  #change name of the service

        auth_request /authelia;
        auth_request_set $target_url $scheme://$http_host$request_uri;
        auth_request_set $user $upstream_http_remote_user;
        auth_request_set $groups $upstream_http_remote_groups;
        proxy_set_header Remote-User $user;
        proxy_set_header Remote-Groups $groups;
        error_page 401 =302 https://auth.domain.com/?rd=$target_url;

        client_body_buffer_size 128k;

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

        send_timeout 5m;
        proxy_read_timeout 360;
        proxy_send_timeout 360;
        proxy_connect_timeout 360;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_redirect  http://  $scheme://;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_cache_bypass $cookie_session;
        proxy_no_cache $cookie_session;
        proxy_buffers 64 256k;

        # add your ip range here, and remove this comment!
        set_real_ip_from 192.168.0.0/16;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
    }
```

## SilverBullet Docker compose

```yml
  silverbullet:
    container_name: silverbullet
    image: zefhemel/silverbullet
    volumes:
      - /media/docker/silverbullet/space:/space
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SB_USER=${USERNAME}:${PASSWORD}
```

The .env files is as follows:

```zsh
USERNAME=USER
PASSWORD=REDACTED
```

Hope this helps
