### ISSUE TITLE
Nicer way to change keyboard shortcuts

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#605]
While technically it's possible to remap (most) keyboards shortcuts, it's not very user friendly: https://silverbullet.md/SETTINGS

I'm open to suggestions on how to do this better. Likely this should still happen in `SETTINGS` but I'm open to a format.

Some spitballing:

```yaml
keyboard:
   "Stats: Show":
      key: "Ctrl-Alt-s"
      mac: "Cmd-Alt-s"
```

**Comment by zefhemel** [comment]
Ultimately went with this format:

```
# Keyboard shortcut overrides take presedence over built-in shortcuts
keyboardShortcuts:
  # Using the command-link syntax
  - command: "{[Stats: Show]}"
    # Mac-specific keyboard
    mac: "Cmd-s"
    # Key binding for Windows/Linux (and Mac if not defined)
    key: "Ctrl-s"
  - command: "Navigate: Center Cursor"
    key: "Alt-x"
```
