### ISSUE TITLE
validate plug yaml

### ISSUE THREAD

**Issue by Willyfrog** [silverbulletmd/silverbullet#61]
yaml is very flexible, and sometimes that allows for creating some typos that might not be caught until hours later of dimissing any other possible cause.

having a yaml validator that issues a warning (we should keep the flexibility) when building a plug, would probably help figuring out some of this problems beforehand.

In my specific case my yaml was like:
```yaml
name: mattermost
functions:
  postUnfurlOptions:
    path: ./channels.ts:unfurlOptions
    event: unfurl:options
  postUnfurl:
    path: ./channels.ts:unfurl
    event: unfurl:mattermost-unfurl
```

which caused the unfurl event to not dispatch and later on it didn't apply the function (yes, I failed twice on the same spot 🤦🏼 )

having some basic structure validation on build, could have prevented that on the first attempt to build it.
