### ISSUE TITLE
Make buttons in top bar configurable

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#643]
Via SETTINGS, conceptually:

```yaml
topButtons:
- icon: home
  command: "Navigate: Home"
- icon: terminal
  command: "Command Palette"
```
