### ISSUE TITLE
Page navigation doesn't work anymore when aliases is not a list

### ISSUE THREAD

**Issue by Melkor333** [silverbulletmd/silverbullet#656]
I've had the page selection break completely because I accidentally put something like to following into a page:

```yaml
---
tags:
  - person
first-name: Firstname
last-name: lastname
aliases: first
```
It showed the following error in the console:

![image](https://github.com/silverbulletmd/silverbullet/assets/6412377/a135a560-08a6-4b2f-a661-46cb0a4c62d7)

The fix is obviously to replace `aliases: first` with 
```yaml
aliases:
- first
```

But it's still a bit annoying that the application pretty much completely breaks (no page navigation except clicking on links) because of this with only an ugly error in the console.
