### ISSUE TITLE
Timezone ignored on Docker container

### ISSUE THREAD

**Issue by rc2dev** [silverbulletmd/silverbullet#680]
First of all, thanks for Silverbullet!

I have a command to create a note with name `"{{ today }} {{ time }}"`. However, time is UTC instead of local.

My compose.yaml:

```yaml
services:
  silverbullet:
    image: zefhemel/silverbullet
    container_name: silverbullet
    restart: unless-stopped
    environment:
      - SB_USER=${USERNAME}:${PASSWORD}
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/dietpi_userdata/silverbullet:/space
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
```

Running `date` inside the container returns UTC time.

I've also tried, with no luck:

```yaml
   volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
 ```
