### ISSUE TITLE
Keep space settings in `SETTINGS` page

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#8]
Similar to the “built-in” `PLUGS` page, we can also have a `SETTINGS` page in which we keep a YAML block with various space-specific settings. 

Examples could include:

* A configurable prefix for page templates for the “instantiate page template” command (currently hardcoded)
* A configurable prefix for the snippet command (currently hardcoded)
* Any other plug-specific settings plugs may need (perhaps nested, e.g. a “ghost” top-level key, with more ghost-specific settings nested under it)

Example SETTINGS page:

      This is your SETTINGS file, bladiedah.

      ```yaml
      snippetPrefix: snippets/
      pageTemplatePrefix: templates/pages/
      ghost:
           url: https://zef.ghost.io
      ```

Possible future commands/plugs can implement a nice UI on top of this `SETTINGS` file, so you don’t have to edit YAML by hand.
