### ISSUE TITLE
Incompatibility Between #boot URL and indexPage: "Journal/day/{{today}}"

### ISSUE THREAD

**Issue by daydaya** [silverbulletmd/silverbullet#955]
## Problem Description
I am using the latest edge Docker version. 
I have set the homepage as: `indexPage: "Journal/day/{{today}}"`.

When there is no entry for the current day, launching the app in PWA mode causes the journal template's content to be directly added to the last accessed page. Sometimes it even replaces the content of the last accessed page with the journal template, instead of correctly creating and opening a new entry for the current day.

## My Attempts
#888 
Currently, when adding a PWA, the URL defaults to including `#boot`. When I remove `#boot`, everything works fine. However, the problem is that it seems impossible to customize the PWA URL on Windows and iOS.

## My Settings
SETTINGS:
```
indexPage: "Journal/day/{{today}}"
```

Daily Note:
```
description: "Your daily note template"
tags: template
hooks.newPage:
  suggestedName: "Journal/day/{{today}}"
  confirmName: false
  openIfExists: true
  forPrefix: "Journal/day"
  command: "Open Daily Note"
  key: "Alt-Shift-d"
```
